services:
  - type: web
    name: asteroid-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: NASA_API_KEY
        sync: false  # ⚠️ SET THIS MANUALLY IN RENDER DASHBOARD - NEVER COMMIT API KEYS!
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: FRONTEND_URL
        value: http://localhost:3000  # Update with your frontend domain after deployment
